apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mammoth-tarantula-python 
  janus-idp.io/tekton: mammoth-tarantula-python
  backstage.io/kubernetes-id: mammoth-tarantula-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mammoth-tarantula-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  