apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mammoth-tarantula-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mammoth-tarantula-python 
  name: mammoth-tarantula-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mammoth-tarantula-python 
